spring.profiles.active=JDBC
spring.application.name=frauddetection
server.port=8082
spring.datasource.url=jdbc:mysql://localhost:3306/fraud_detection?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=n3u3da!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.mode=always
